### ISSUE TITLE
[e10s] "Cut" and "Copy" commands are broken

### ISSUE THREAD

**Issue by Keith94** [vovcacik/cut-copy-paste-tabs#3]
Only "Paste" works correctly with e10s enabled. Trying to use Cut/Copy adds the following to browser console

```
unsafe/forbidden CPOW usage  RemoteAddonsParent.jsm:881:2
unsafe/forbidden CPOW usage  browserOverlay.js:133:29
unsafe/forbidden CPOW usage  browserOverlay.js:134:20
unsafe/forbidden CPOW usage browserOverlay.js:134:34
NS_ERROR_XPC_CANT_PASS_CPOW_TO_NATIVE: It's illegal to pass a CPOW to native code arg 0 [nsITransferable.init]  browserOverlay.js:137
```

**Comment by Keith94** [comment]
Oh sorry, duplicate of #2. Is there any progress with this issue?

**Comment by vovcacik** [comment]
No, sorry. The e10s will deprecate many addons and this one will be one of them.

**Comment by Keith94** [comment]
Too bad, I'll have to look for another add-on for pasting tabs. Let me know if you have any recommendations.
